<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.4.3" />
        <PackageReference Include="Scalar.AspNetCore.Swashbuckle" Version="2.4.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MetricsApp.Abstractions\MetricsApp.Abstractions.csproj" />
      <ProjectReference Include="..\MetricsApp.Cache.InMemory\MetricsApp.Cache.InMemory.csproj" />
      <ProjectReference Include="..\MetricsApp.Parser.WindowsPerfCounters\MetricsApp.Parser.WindowsPerfCounters.csproj" />
      <ProjectReference Include="..\MetricsApp.Queue.InMemory\MetricsApp.Queue.InMemory.csproj" />
      <ProjectReference Include="..\MetricsApp.Repository.InMemory\MetricsApp.Repository.InMemory.csproj" />
      <ProjectReference Include="..\MetricsApp.Worker\MetricsApp.Worker.csproj" />
    </ItemGroup>

</Project>
