<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.4.8" />
        <PackageReference Include="Scalar.AspNetCore.Swashbuckle" Version="2.4.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MetricsApp.Abstractions\MetricsApp.Abstractions.csproj" />
      <ProjectReference Include="..\MetricsApp.Agent.Collectors.WindowsPerfCounters\MetricsApp.Agent.Collectors.WindowsPerfCounters.csproj" />
      <ProjectReference Include="..\MetricsApp.Agent.Core\MetricsApp.Agent.Core.csproj" />
      <ProjectReference Include="..\MetricsApp.Cache.InMemory\MetricsApp.Cache.InMemory.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.Core\MetricsApp.DataSources.Core.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.MySql\MetricsApp.DataSources.MySql.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.PostgreSQL\MetricsApp.DataSources.PostgreSQL.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.Prometheus\MetricsApp.DataSources.Prometheus.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.Redis\MetricsApp.DataSources.Redis.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.Sqlite\MetricsApp.DataSources.Sqlite.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.SqlServer\MetricsApp.DataSources.SqlServer.csproj" />
      <ProjectReference Include="..\MetricsApp.DataSources.WindowsPerformanceCounters\MetricsApp.DataSources.WindowsPerformanceCounters.csproj" />
      <ProjectReference Include="..\MetricsApp.Parser.WindowsPerfCounters\MetricsApp.Parser.WindowsPerfCounters.csproj" />
      <ProjectReference Include="..\MetricsApp.Queue.InMemory\MetricsApp.Queue.InMemory.csproj" />
      <ProjectReference Include="..\MetricsApp.Repository.InMemory\MetricsApp.Repository.InMemory.csproj" />
      <ProjectReference Include="..\MetricsApp.Worker\MetricsApp.Worker.csproj" />
    </ItemGroup>

</Project>
