<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Content Update="manifest.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MetricsApp.Abstractions\MetricsApp.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="schema.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="manifest.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
